### ISSUE TITLE
External host issue

### ISSUE THREAD

**Issue by slick122** [sdr-enthusiasts/docker-radarbox#174]
rbfeeder] getaddrinfo: Name or service not known
[rbfeeder] [2023-07-30 10:05:10]  Could not resolve host name specified in 'external_host'.

Any idea where I should start?

**Comment by Andysimcoe** [comment]
Without seeing your Docker run command I will guess it's a malformed hostname. 

Example:
 -e BEASTHOST=127.0.0.1 \

I'm able to reproduce your error if I set that to include the port "127.0.0.1:30005", the port is a different environment variable but defaults to 30005, so make sure you're not doing that. If you need to specify a port other than 30005, use BEASTPORT.
