### ISSUE TITLE
Bring back MLAT_INPUT_TYPE

### ISSUE THREAD

**Issue by labuwx** [sdr-enthusiasts/docker-radarbox#75]
Hi,

The `MLAT_INPUT_TYPE` variable was added in #17 but removed in #48.
I use a `radarcape_gps` style receiver, for which I would need to change this parameter.

Can you please add back this variable?

**Comment by mikenye** [comment]
I'd like to, but I'm not sure `rbfeeder` will support it.

Looking at their newly released source code, this line appears to be what starts mlat_client:

https://github.com/AirNav-Systems/rbfeeder/blob/3d9e53320e792251982d4ead14c19aadd54541b0/airnav_mlat.c#L56

```c
        sprintf(tmp_cmd, "%s --input-type dump1090 --input-connect 127.0.0.1:%s --server %s --lat %f --lon %f --alt %d --user %s --results beast,connect,127.0.0.1:%s", mlat_cmd, beast_out_port, mlat_server, g_lat, g_lon, g_alt, sn, beast_in_port);
```

As you can see, `--input-type` is hard-coded to `dump1090`.

We would need AirNav to be able to read the input type from rbfeeder.ini or as a command-line argument to `rbfeeder`.

Did you want to open an issue on their repo?
